services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # On ne publie plus le port 5432 sur l'hôte en production pour la sécurité

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_app
    restart: always
    environment:
      - DEBUG=0  # Désactiver le debug en production
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - static_volume:/app/static

  vue:
    build:
      context: ./project-management
      dockerfile: ../Dockerfile.vue
    container_name: nginx_vue
    restart: always
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - static_volume:/app/static # Pour que Nginx serve les fichiers de Django

volumes:
  postgres_data:
  static_volume:
