# Generated by Django 5.2.8 on 2025-11-18 10:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manager.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(help_text='Code court pour référencement', max_length=20, unique=True, verbose_name='Code')),
                ('couleur', models.CharField(default='#3498db', help_text="Couleur hex pour l'interface (#RRGGBB)", max_length=7, verbose_name='Couleur')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: file-text, certificate, etc.)", max_length=50, verbose_name='Icône')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='manager.categoriedocument', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('PERSONNE_PHYSIQUE', 'Personne Physique'), ('PERSONNE_MORALE', 'Personne Morale')], max_length=20, verbose_name='Type de client')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('PROSPECT', 'Prospect'), ('ARCHIVE', 'Archivé')], default='PROSPECT', max_length=10, verbose_name='Statut')),
                ('reference_client', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence client')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(blank=True, max_length=100, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, max_length=50, verbose_name='Forme juridique')),
                ('numero_rccm', models.CharField(blank=True, max_length=50, verbose_name='Numéro RCCM')),
                ('numero_cc', models.CharField(blank=True, max_length=50, verbose_name='Numéro Compte Contribuable')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital social')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('telephone_1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+225XXXXXXXXXX' ou 'XXXXXXXXXX'", regex='^\\+?[0-9]{8,15}$')], verbose_name='Téléphone 1')),
                ('telephone_2', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+225XXXXXXXXXX' ou 'XXXXXXXXXX'", regex='^\\+?[0-9]{8,15}$')], verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('representant_legal_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du représentant légal')),
                ('representant_legal_fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction du représentant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_premier_contact', models.DateField(default=django.utils.timezone.now, verbose_name='Date premier contact')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur le client', verbose_name='Notes')),
                ('charge_de_clientele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_geres', to=settings.AUTH_USER_MODEL, verbose_name='Chargé de clientèle')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_dossier', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence dossier')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du dossier')),
                ('type_dossier', models.CharField(choices=[('CONSTITUTION', 'Constitution de société'), ('MODIFICATION', 'Modification statutaire'), ('DISSOLUTION', 'Dissolution/Liquidation'), ('CONTENTIEUX', 'Contentieux'), ('CONSEIL', 'Conseil juridique'), ('CONTRAT', 'Rédaction de contrat'), ('AUDIT', 'Audit juridique'), ('PROPRIETE_INTELLECTUELLE', 'Propriété intellectuelle'), ('FUSION_ACQUISITION', 'Fusion/Acquisition'), ('RECOUVREMENT', 'Recouvrement de créances'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type de dossier')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente (client)'), ('BLOQUE', 'Bloqué'), ('TERMINE', 'Terminé'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='NOUVEAU', max_length=15, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorité')),
                ('date_ouverture', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('date_derniere_activite', models.DateTimeField(auto_now=True, verbose_name='Date dernière activité')),
                ('honoraires_prevus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Honoraires prévus (FCFA)')),
                ('honoraires_factures', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Honoraires facturés (FCFA)')),
                ('acompte_recu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Acompte reçu (FCFA)')),
                ('numero_tribunal', models.CharField(blank=True, max_length=100, verbose_name='Numéro tribunal/greffe')),
                ('juridiction', models.CharField(blank=True, max_length=100, verbose_name='Juridiction compétente')),
                ('numero_rg', models.CharField(blank=True, max_length=100, verbose_name='Numéro RG (Rôle Général)')),
                ('observations', models.TextField(blank=True, verbose_name='Observations internes')),
                ('actions_requises', models.TextField(blank=True, verbose_name='Actions à effectuer')),
                ('est_archive', models.BooleanField(default=False, verbose_name='Archivé')),
                ('localisation_physique', models.CharField(blank=True, help_text='Emplacement physique du dossier (armoire, étagère...)', max_length=200, verbose_name='Localisation physique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('avocat_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Avocat responsable')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='manager.client', verbose_name='Client principal')),
                ('collaborateurs', models.ManyToManyField(blank=True, related_name='dossiers_collabores', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_ouverture', '-date_creation'],
                'permissions': [('view_all_dossiers', 'Peut voir tous les dossiers'), ('archive_dossier', 'Peut archiver un dossier'), ('manage_financial', 'Peut gérer les aspects financiers')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Référence du document')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_document', models.CharField(choices=[('PIECE_IDENTITE', "Pièce d'identité"), ('STATUT', 'Statuts'), ('PROCES_VERBAL', 'Procès-verbal'), ('CONTRAT', 'Contrat'), ('COURRIER', 'Courrier'), ('ATTESTATION', 'Attestation'), ('CERTIFICAT', 'Certificat'), ('FACTURE', 'Facture'), ('RECU', 'Reçu'), ('ACTE', 'Acte juridique'), ('JUGEMENT', 'Jugement'), ('ORDONNANCE', 'Ordonnance'), ('ASSIGNATION', 'Assignation'), ('CONCLUSIONS', 'Conclusions'), ('MEMOIRE', 'Mémoire'), ('RAPPORT', 'Rapport'), ('NOTE', 'Note juridique'), ('CORRESPONDANCE', 'Correspondance'), ('FORMULAIRE', 'Formulaire administratif'), ('JUSTIFICATIF', 'Justificatif'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to=manager.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'jpg', 'jpeg', 'png', 'xlsx', 'xls', 'zip'])], verbose_name='Fichier')),
                ('taille_fichier', models.BigIntegerField(editable=False, null=True, verbose_name='Taille du fichier (octets)')),
                ('extension', models.CharField(blank=True, editable=False, max_length=10, verbose_name='Extension')),
                ('numero_document', models.CharField(blank=True, help_text='Numéro officiel du document (ex: numéro de jugement, numéro RCCM, etc.)', max_length=100, verbose_name='Numéro document')),
                ('date_document', models.DateField(blank=True, help_text='Date de création/signature du document original', null=True, verbose_name='Date du document')),
                ('date_validite', models.DateField(blank=True, help_text="Date jusqu'à laquelle le document est valide", null=True, verbose_name='Date de validité')),
                ('emetteur', models.CharField(blank=True, help_text='Personne ou organisme émetteur du document', max_length=200, verbose_name='Émetteur/Auteur')),
                ('destinataire', models.CharField(blank=True, max_length=200, verbose_name='Destinataire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('SIGNE', 'Signé'), ('ENVOYE', 'Envoyé'), ('ARCHIVE', 'Archivé'), ('PERIME', 'Périmé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=25, verbose_name='Statut')),
                ('niveau_confidentialite', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNE', 'Interne'), ('CONFIDENTIEL', 'Confidentiel'), ('TRES_CONFIDENTIEL', 'Très confidentiel')], default='INTERNE', max_length=20, verbose_name='Niveau de confidentialité')),
                ('est_original', models.BooleanField(default=False, help_text="Cocher si c'est l'original physique ou numérique", verbose_name='Document original')),
                ('est_certifie_conforme', models.BooleanField(default=False, verbose_name='Certifié conforme')),
                ('necessite_signature', models.BooleanField(default=False, verbose_name='Nécessite signature')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date validation')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules pour faciliter la recherche', max_length=500, verbose_name='Tags')),
                ('mots_cles', models.TextField(blank=True, help_text='Mots-clés pour la recherche full-text', verbose_name='Mots-clés')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('derniere_consultation', models.DateTimeField(blank=True, null=True, verbose_name='Dernière consultation')),
                ('nombre_consultations', models.PositiveIntegerField(default=0, verbose_name='Nombre de consultations')),
                ('notes_internes', models.TextField(blank=True, help_text="Notes visibles uniquement par l'équipe", verbose_name='Notes internes')),
                ('est_archive', models.BooleanField(default=False, verbose_name='Est archivé')),
                ('date_archivage', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='manager.categoriedocument', verbose_name='Catégorie')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='manager.client', verbose_name='Client associé')),
                ('document_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='manager.document', verbose_name='Document parent (version précédente)')),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='manager.dossier', verbose_name='Dossier associé')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
                'permissions': [('view_confidential_documents', 'Peut voir les documents confidentiels'), ('validate_document', 'Peut valider un document'), ('sign_document', 'Peut signer un document'), ('archive_document', 'Peut archiver un document')],
            },
        ),
        migrations.CreateModel(
            name='EtapeDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'étape")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('est_terminee', models.BooleanField(default=False, verbose_name='Est terminée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='manager.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Étape de dossier',
                'verbose_name_plural': 'Étapes de dossier',
                'ordering': ['dossier', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('CONSULTATION', 'Consultation'), ('TELECHARGEMENT', 'Téléchargement'), ('VALIDATION', 'Validation'), ('SIGNATURE', 'Signature'), ('ENVOI', 'Envoi'), ('ARCHIVAGE', 'Archivage'), ('SUPPRESSION', 'Suppression'), ('PARTAGE', 'Partage')], max_length=20, verbose_name='Action')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date action')),
                ('details', models.TextField(blank=True, help_text="Détails supplémentaires sur l'action", verbose_name='Détails')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='manager.document')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de document',
                'verbose_name_plural': 'Historiques de documents',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='SignatureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_signature', models.PositiveIntegerField(default=1, help_text='Ordre dans lequel le signataire doit signer', verbose_name='Ordre signature')),
                ('a_signe', models.BooleanField(default=False, verbose_name='A signé')),
                ('date_signature', models.DateTimeField(blank=True, null=True, verbose_name='Date signature')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('empreinte_numerique', models.CharField(blank=True, help_text='Hash SHA-256 du document au moment de la signature', max_length=64, verbose_name='Empreinte numérique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='manager.document')),
                ('signataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature de document',
                'verbose_name_plural': 'Signatures de documents',
                'ordering': ['document', 'ordre_signature'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='signataires',
            field=models.ManyToManyField(related_name='documents_a_signer', through='manager.SignatureDocument', to=settings.AUTH_USER_MODEL, verbose_name='Signataires'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['reference_client'], name='manager_cli_referen_bdab15_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['type_client', 'statut'], name='manager_cli_type_cl_9e51ed_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['raison_sociale'], name='manager_cli_raison__5f8d43_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom', 'prenoms'], name='manager_cli_nom_067c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['reference_dossier'], name='manager_dos_referen_1fdaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['client', 'statut'], name='manager_dos_client__ba0eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['avocat_responsable', 'statut'], name='manager_dos_avocat__dce7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['type_dossier', 'statut'], name='manager_dos_type_do_e1bcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['date_echeance'], name='manager_dos_date_ec_173382_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['-date_derniere_activite'], name='manager_dos_date_de_f3f3c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signaturedocument',
            unique_together={('document', 'signataire')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference'], name='manager_doc_referen_1182e3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dossier', 'statut'], name='manager_doc_dossier_8e1afc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client', 'type_document'], name='manager_doc_client__304962_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type_document', 'statut'], name='manager_doc_type_do_6cdc40_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date_document'], name='manager_doc_date_do_e7df74_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date_validite'], name='manager_doc_date_va_7fb5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-date_upload'], name='manager_doc_date_up_d6a0e3_idx'),
        ),
    ]
