# Generated by Django 5.2.8 on 2025-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dossier',
            name='manager_dos_avocat__dce7e4_idx',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='avocat_responsable',
        ),
        migrations.AddField(
            model_name='dossier',
            name='chemin_dossier',
            field=models.CharField(blank=True, editable=False, max_length=500, verbose_name='Chemin du dossier'),
        ),
    ]
