# Generated by Django 5.2.8 on 2025-11-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_dossier_manager_dos_avocat__dce7e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('PROSPECT', 'Prospect'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=10, verbose_name='Statut'),
        ),
    ]
