# Generated by Django 5.2.8 on 2025-11-27 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_client_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='collaborateurs',
            field=models.ManyToManyField(blank=True, null=True, related_name='dossiers_collabores', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs'),
        ),
        migrations.AlterUniqueTogether(
            name='dossier',
            unique_together={('titre', 'client')},
        ),
    ]
