# Generated by Django 5.2.8 on 2025-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_dossier_collaborateurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriedocument',
            name='est_fondamentale',
            field=models.BooleanField(default=False, verbose_name='Document fondamental'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('AJOUT_PIECE', 'ajouts piece'), ('DOCU_FONDA', 'Documents fondamentaux'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente (client)'), ('BLOQUE', 'Bloqué'), ('TERMINE', 'Terminé'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='NOUVEAU', max_length=15, verbose_name='Statut'),
        ),
    ]
