# Generated by Django 5.2.8 on 2025-12-04 11:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_categoriedocument_est_fondamentale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='manager_doc_client__304962_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='manager_doc_type_do_6cdc40_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type_document',
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='poids',
            field=models.IntegerField(default=10, help_text="Importance de cette catégorie dans l'avancement global (1-100)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="Poids dans l'avancement"),
        ),
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='manager.categoriedocument', verbose_name='Catégorie'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client', 'categorie'], name='manager_doc_client__207e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['categorie', 'statut'], name='manager_doc_categor_d75913_idx'),
        ),
    ]
