# Generated by Django 5.2.8 on 2025-12-04 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_document_manager_doc_client__304962_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriedocument',
            name='delai_max',
            field=models.IntegerField(blank=True, help_text='Délai maximum pour obtenir ce type de document', null=True, verbose_name='Délai maximum (jours)'),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='est_obligatoire',
            field=models.BooleanField(default=False, help_text='Cette catégorie est-elle obligatoire pour terminer le dossier ?', verbose_name='Obligatoire'),
        ),
        migrations.AlterField(
            model_name='document',
            name='numero_document',
            field=models.CharField(blank=True, help_text='Numéro officiel du document', max_length=100, verbose_name='Numéro document'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='collaborateurs',
            field=models.ManyToManyField(blank=True, related_name='dossiers_collabores', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs'),
        ),
    ]
