# Generated by Django 5.2.8 on 2025-12-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_categoriedocument_delai_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='est_archive',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente (client)'), ('BLOQUE', 'Bloqué'), ('TERMINE', 'Terminé'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé'), ('ANNULE', 'Annulé')], default='NOUVEAU', max_length=15, verbose_name='Statut'),
        ),
    ]
