# Generated by Django 5.2.8 on 2025-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_dossier_est_archive_alter_dossier_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='est_archive',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
