# Generated by Django 5.2.8 on 2025-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_dossier_est_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente (client)'), ('BLOQUE', 'Bloqué'), ('TERMINE', 'Terminé'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='NOUVEAU', max_length=15, verbose_name='Statut'),
        ),
    ]
