# Generated by Django 5.2.8 on 2025-12-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_dossier_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='acompte_recu',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='honoraires_factures',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='honoraires_prevus',
        ),
    ]
