# Generated by Django 5.2.8 on 2025-12-08 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('DOSSIER_CREATION', 'Dossier créé'), ('DOSSIER_MISE_A_JOUR', 'Dossier mis à jour'), ('DOCUMENT_TELEVERSE', 'Document téléversé'), ('DOCUMENT_SUPPRIME', 'Document supprimé'), ('CLIENT_AJOUTE', 'Nouveau client ajouté')], max_length=50, verbose_name='Action')),
                ('message', models.TextField(verbose_name='Message de notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('object_id', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
