# Generated by Django 5.2.8 on 2026-02-09 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre explicite de l'information", max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='URL conviviale pour le référencement', max_length=250, unique_for_date='publication_date', verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Court résumé (max 500 caractères)', max_length=500, verbose_name='Résumé')),
                ('content', models.TextField(help_text="Contenu détaillé de l'information", verbose_name='Contenu')),
                ('category', models.CharField(choices=[('technology', 'Technologie'), ('strategy', 'Stratégie'), ('marketing', 'Marketing'), ('finance', 'Finances'), ('hr', 'Ressources Humaines'), ('operations', 'Opérations'), ('sales', 'Ventes'), ('innovation', 'Innovation'), ('general', 'Général')], default='general', max_length=50, verbose_name='Catégorie')),
                ('confidentiality_level', models.IntegerField(choices=[(1, 'Public (Tous les employés)'), (2, 'Interne (Employés confirmés)'), (3, 'Confidentiel (Managers+)'), (4, 'Restreint (Direction)')], default=2, verbose_name='Niveau de confidentialité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé'), ('restricted', 'Accès restreint')], default='draft', max_length=50, verbose_name='Statut')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de publication planifiée', verbose_name='Date de publication')),
                ('expiration_date', models.DateTimeField(blank=True, help_text="Date à laquelle l'information n'est plus pertinente", null=True, verbose_name="Date d'expiration")),
                ('attachment', models.FileField(blank=True, null=True, upload_to='insights/attachments/%Y/%m/%d/', verbose_name='Pièce jointe')),
                ('thumbnail', models.ImageField(blank=True, help_text='Image représentative (format recommandé: 1200x630px)', null=True, upload_to='insights/thumbnails/%Y/%m/%d/', verbose_name='Image de couverture')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher en première page', verbose_name='Mettre en avant')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Autoriser les commentaires')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('related_insights', models.ManyToManyField(blank=True, to='notification.insight', verbose_name='Informations connexes')),
            ],
            options={
                'verbose_name': 'Information interne',
                'verbose_name_plural': 'Informations internes',
                'ordering': ['-publication_date', '-creation_date'],
                'permissions': [('view_confidential', 'Peut voir les informations confidentielles'), ('publish_insight', 'Peut publier des informations'), ('manage_insights', 'Peut gérer toutes les informations')],
                'indexes': [models.Index(fields=['status', 'publication_date'], name='notificatio_status_fb356e_idx'), models.Index(fields=['category', 'confidentiality_level'], name='notificatio_categor_45420b_idx')],
            },
        ),
    ]
